# This is an ubuntu 20.04 LTS based image
#image: atlassian/default-image:3
image: mcr.microsoft.com/devcontainers/base:jammy
pipelines:
  default:    
    - step:
        name: 'Test'
        script:
          - ./scripts/setup.sh
          - ./scripts/test.sh
    - step:
        name: 'Build'
        script:
          - ./scripts/build.sh
    - step:
        name: 'Build Documentation'
        script:
          - ./scripts/build-docu.sh
       
      
