# This is an ubuntu 20.04 LTS based image
image: atlassian/default-image:3
options:
  docker: true
pipelines:
  branches:
    release/*:
      - parallel:
          - step:
              name: 'Test: Ansible 2.14 (python-3.11)'
              image: python:3.11-bullseye
              script:
                - ./scripts/test.sh 3.11 2.14
          - step:
              name: 'Test: Ansible 2.15 (devel) (python-3.11)'
              image: python:3.11-bullseye
              script:
                - ./scripts/test-devel.sh 3.11
          - step:
              name: 'Test: Ansible 2.12 (python-3.10)'
              image: python:3.10-bullseye
              script:
                - ./scripts/test.sh 3.10 2.12 2.13
          - step:
              name: 'Test: Ansible 2.13 (python-3.10)'
              image: python:3.10-bullseye
              script:
                - ./scripts/test.sh 3.10 2.13 2.14
          - step:
              name: 'Test: Ansible 2.14 (python-3.10)'
              image: python:3.10-bullseye
              script:
                - ./scripts/test.sh 3.10 2.14
          - step:
              name: 'Test: Ansible 2.15 (devel) (python-3.10)'
              image: python:3.10-bullseye
              script:
                - ./scripts/test-devel.sh 3.10
          - step:
              name: 'Test: Ansible 2.12 (python-3.9)'
              image: python:3.9-bullseye
              script:
                - ./scripts/test.sh 3.9 2.12 2.13
          - step:
              name: 'Test: Ansible 2.13 (python-3.9)'
              image: python:3.9-bullseye
              script:
                - ./scripts/test.sh 3.9 2.13 2.14
          - step:
              name: 'Test: Ansible 2.14 (python-3.9)'
              image: python:3.9-bullseye
              script:
                - ./scripts/test.sh 3.9 2.14
          - step:
              name: 'Test: Ansible 2.15 (devel) (python-3.9)'
              image: python:3.9-bullseye
              script:
                - ./scripts/test-devel.sh 3.9
          - step:
              name: 'Test: Ansible 2.12 (python-3.8)'
              image: python:3.8-bullseye
              script:
                - ./scripts/test.sh 3.8 2.12 2.13
          - step:
              name: 'Test: Ansible 2.13 (python-3.8)'
              image: python:3.8-bullseye
              script:
                - ./scripts/test.sh 3.8 2.13 2.14
      - step:
          name: 'Build with Ansible 2.14 and python-3.11'
          image: python:3.11-bullseye
          script:
            - ./scripts/build.sh 2.14
          artifacts:
            - build/**
      - step:
          name: 'Build Documentation'
          image: python:3.9-bullseye
          script:
            - ./scripts/build-docu.sh 2.14
          artifacts:
            - build/**

