# This is an ubuntu 20.04 LTS based image
image: atlassian/default-image:3
options:
  docker: true
pipelines:
  default:    
    - step:
        name: 'Test: Python 3.9'
        image: python:3.10-bullseye
        script:
          - ./scripts/test.sh 2.13
    - step:
        name: 'Build'
        script:
          - ./scripts/build.sh
    - step:
        name: 'Build Documentation'
        script:
          - ./scripts/build-docu.sh
       
      
