# ansible-playbook simple-playbook.yml
- hosts: localhost
  vars:
    avantra_api_url: http://localhost:8090/xn
    avantra_api_user: mis2
    avantra_api_password: REDACTED

  tasks:

    - name: Login to Avantra API and fetch a token
      avantra.core.login:
      register: auth

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: auth.token

    - name: RESTART SMA_REMOTE2
      avantra.core.sapsystem_restart:
        avantra_token: "{{auth.token}}"
        unified_sap_sid: "SMA_REMOTE2"
        customer_name: "mis"
      register: restart_result

    - name: restart_result
      ansible.builtin.debug:
        var: restart_result

    - name: RESTART SMA_REMOTE2
      avantra.core.sapsystem_restart:
        avantra_token: "{{auth.token}}"
        unified_sap_sid: "SMA_REMOTE2"
        customer_name: "mis"
        with_database: true
        with_servers: true
      register: restart_result

    - name: restart_result
      ansible.builtin.debug:
        var: restart_result

    - name: RESTART SMA_REMOTE2
      avantra.core.sapsystem_start:
        avantra_token: "{{auth.token}}"
        unified_sap_sid: "SMA_REMOTE2"
        customer_name: "mis"
        with_database: true
        with_servers: true
      register: restart_result

    - name: restart_result
      ansible.builtin.debug:
        var: restart_result

    - name: RESTART SMA_REMOTE2
      avantra.core.sapsystem_stop:
        avantra_token: "{{auth.token}}"
        unified_sap_sid: "SMA_REMOTE2"
        customer_name: "mis"
        with_database: true
        with_servers: true
      register: restart_result

    - name: restart_result
      ansible.builtin.debug:
        var: restart_result
