# ansible-playbook simple-playbook.yml
- hosts: localhost
  vars:
    avantra_api_url: http://localhost:8090/xn
    avantra_api_user: mis2
    avantra_api_password: 111111111111

  tasks:

    - name: Login to Avantra API and fetch a token
      avantra.core.login:
      register: auth

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: auth.token

    - name: "Start server: achnmc-mis2"
      avantra.core.server_start:
        avantra_token: "{{auth.token}}"
        server_name: "achnmn-mis2"
        customer_name: "mis"
      register: start_result

    - name: start_result
      ansible.builtin.debug:
        var: start_result

    - name: "Stop server: achnmc-mis2"
      avantra.core.server_stop:
        avantra_token: "{{auth.token}}"
        server_name: "achnmn-mis2"
        customer_name: "mis"
      register: stop_result

    - name: stop_result
      ansible.builtin.debug:
        var: stop_result
