# ansible-playbook simple-playbook.yml
- hosts: localhost
  vars:
    avantra_api_url: http://localhost:8090/xn
    avantra_api_user: mis2
    avantra_api_password: 111111111111

  tasks:

    - name: Login to Avantra API and fetch a token
      avantra.core.login:
      register: auth

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: auth.token

    - name: Try to find server achnmc-mis2
      avantra.core.server_get:
        avantra_token: "{{auth.token}}"
        server_name: "achnmn-mis2"
        customer_name: "mis"
        fail_if_not_found: false
      register: find_server

    - name: find_server
      ansible.builtin.debug:
        var: find_server

    - name: Create Server
      avantra.core.server_create:
        avantra_token: "{{auth.token}}"
        server_name: "achnmn-mis2"
        customer_name: "mis"
        fqdn_or_ip_address: "localhost"
        system_role: "Test"
        credentials:
          avantra.basic:
            cred_type: basic
            username: mickey
            password: mouse
          avantra.abc:
            cred_type: ssh
            username: mickey
            password: mouse
            hostname: home
            port: 4321
            config:
              hello: world
      register: create_server
      when: find_server.server == None

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: create_server
