# ansible-playbook simple-playbook.yml
- hosts: localhost
  vars:
    avantra_api_url: http://localhost:8090/xn
    avantra_api_user: mis2
    avantra_api_password: 111111111111

  tasks:

    - name: Login to Avantra API and fetch a token
      avantra.core.login:
      register: auth

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: auth.token

    - name: Load information for a SAP system via the system ID 5
      avantra.core.sapsystem_get:
        avantra_token: "{{auth.token}}"
        system_id: 5

    - name: Load information for a SAP system via the Unified SAP SID and customer name
      avantra.core.sapsystem_get:
        avantra_token: "{{auth.token}}"
        unified_sap_sid: SMA_REMOTE
        customer_name: mis
      register: result

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result

    - name: Load information for a SAP system via the system ID 7
      avantra.core.sapsystem_get:
        avantra_token: "{{auth.token}}"
        system_id: 7
        fail_if_not_found: false
      register: find_sap

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: find_sap

    - name: Load information for a server via the system ID 1
      avantra.core.server_get:
        avantra_token: "{{auth.token}}"
        system_id: 1
        fail_if_not_found: true
      register: find_server

    - name: Load information for a server via the server_name and the customer_name
      avantra.core.server_get:
        avantra_token: "{{auth.token}}"
        server_name: "achnmc-mis"
        customer_name: "mis"
        fail_if_not_found: true
      register: find_server

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: find_server
